vhost_traffic_status_zone;

server {
    listen 8080;
    server_name localhost;

    location /status {
        vhost_traffic_status_display;
        vhost_traffic_status_display_format json;
        allow all;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/tmp/app.sock;
        
        uwsgi_param Host $host;
        uwsgi_param X-Real-IP $remote_addr;
        vhost_traffic_status_filter_by_set_key $uri uri;
    }
}
